name = "BloodFlowTrixi"
uuid = "7b46d5ad-635f-4b66-9393-904f183e39b5"
authors = ["yolhan83 <yolhan@laposte.net>"]
version = "0.0.3"

[deps]
Trixi = "a7f1ee26-1774-49b1-8366-f1abc58fbfcb"

[compat]
Trixi = "^0.9.13"
julia = "^1.10"